<<<<<<< HEAD


// "use client";

// import { Provider } from "react-redux";
// import { store } from "@/redux/store";
// import "@/app/globals.css";
// import AuthInitializer from "@/components/AuthInitializer";
// import CartDrawer from "@/components/cart/CartDrawer";
// //import Navbar from "@/components/Navbar";
// import Navbar from "@/components/layout/Navbar";
// import Footer from "@/components/layout/Footer";
// import AnnouncementBar from "../components/layout/AnnouncementBar";




// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>
//         <Provider store={store}>
//           <AuthInitializer />
//           <AnnouncementBar />
//           <Navbar />
//           {children}
//           <Footer />
//           <CartDrawer />
//         </Provider>
//       </body>
//     </html>
//   );
// }




"use client";

import { Provider } from "react-redux";
import { store } from "@/redux/store";
import "@/app/globals.css";
import AuthInitializer from "@/components/AuthInitializer";
=======
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
>>>>>>> 8539fadd8eaafc0a6cc6f0e4364be828fa547c64

export default function RootLayout({ children }) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body>
        <Provider store={store}>
          <AuthInitializer />
          {children}
        </Provider>
      </body>
    </html>
  );
}
=======
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
>>>>>>> 8539fadd8eaafc0a6cc6f0e4364be828fa547c64
